GET http://localhost:8000/api/bears
Accept: application/json

###
POST http://localhost:8000/api/medecins
Content-Type: application/json

{
  "nom": "Mz",
  "prenom": "hedi",
  "inami": 45,
  "email": "azer@hotmail.com",
  "telephone": "04876523",
  "adresse_id": "1",
  "rue": "avenue de vrs",
  "ville": "Bruxelles",
  "code_postal": 1120,
  "mot_de_passe_hash": "1234",
  "mot_de_passe_salt": "1234"

}
###

POST http://localhost:8000/api/login
Content-type: application/json

{
  "email": "azer@hotmail.com",
  "mot_de_passe_hash": "1234"
}






###

